/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package millionaire;

import java.awt.Color;
import java.awt.event.ItemEvent;
import javax.swing.JButton;

/**
 *
 * @author huseyngasimov
 */
public class Game extends javax.swing.JFrame {

    /**
     * Creates new form Game
     */
    
    private char selectedAnswer = 'n';
    private Main mainForm;
    
    
    public Game(Main mainForm) {
        initComponents();
        this.mainForm = mainForm;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlQuestion = new javax.swing.JPanel();
        lblQuestion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        chkFiftyFifty = new javax.swing.JCheckBox();
        chkCallFriend = new javax.swing.JCheckBox();
        chkAuditoryHelp = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        btnAnswerA = new javax.swing.JButton();
        btnAnswerB = new javax.swing.JButton();
        btnAnswerC = new javax.swing.JButton();
        btnAnswerD = new javax.swing.JButton();
        btnWalkAway = new javax.swing.JButton();
        pnlMoney = new javax.swing.JPanel();
        btn100 = new javax.swing.JLabel();
        btn200 = new javax.swing.JLabel();
        btn300 = new javax.swing.JLabel();
        btn500 = new javax.swing.JLabel();
        btn1000 = new javax.swing.JLabel();
        btn2000 = new javax.swing.JLabel();
        btn4000 = new javax.swing.JLabel();
        btn8000 = new javax.swing.JLabel();
        btn1600 = new javax.swing.JLabel();
        btn32000 = new javax.swing.JLabel();
        btn64000 = new javax.swing.JLabel();
        btn125000 = new javax.swing.JLabel();
        btn250000 = new javax.swing.JLabel();
        btn500000 = new javax.swing.JLabel();
        btn1000000 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Who Wants to be a Millionaire?");
        setResizable(false);

        pnlQuestion.setBackground(new java.awt.Color(0, 51, 204));

        lblQuestion.setForeground(new java.awt.Color(255, 255, 255));
        lblQuestion.setText("Question");

        org.jdesktop.layout.GroupLayout pnlQuestionLayout = new org.jdesktop.layout.GroupLayout(pnlQuestion);
        pnlQuestion.setLayout(pnlQuestionLayout);
        pnlQuestionLayout.setHorizontalGroup(
            pnlQuestionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlQuestionLayout.createSequentialGroup()
                .add(296, 296, 296)
                .add(lblQuestion)
                .addContainerGap(307, Short.MAX_VALUE))
        );
        pnlQuestionLayout.setVerticalGroup(
            pnlQuestionLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlQuestionLayout.createSequentialGroup()
                .add(21, 21, 21)
                .add(lblQuestion)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));

        chkFiftyFifty.setForeground(new java.awt.Color(255, 255, 255));
        chkFiftyFifty.setText("Fifty / Fifty");

        chkCallFriend.setForeground(new java.awt.Color(255, 255, 255));
        chkCallFriend.setText("Call Friend");

        chkAuditoryHelp.setForeground(new java.awt.Color(255, 255, 255));
        chkAuditoryHelp.setText("Help of the Auditory");

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("YOUR HELPS:");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(chkFiftyFifty, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(chkCallFriend, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(chkAuditoryHelp, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(15, 15, 15)
                        .add(jLabel1)
                        .add(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(17, 17, 17)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(chkFiftyFifty)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(chkCallFriend)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(chkAuditoryHelp)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnAnswerA.setBackground(new java.awt.Color(0, 51, 204));
        btnAnswerA.setForeground(new java.awt.Color(255, 255, 255));
        btnAnswerA.setText("A: AnswerA");
        btnAnswerA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick_A(evt);
            }
        });

        btnAnswerB.setBackground(new java.awt.Color(0, 51, 204));
        btnAnswerB.setForeground(new java.awt.Color(255, 255, 255));
        btnAnswerB.setText("B: AnswerB");
        btnAnswerB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick_B(evt);
            }
        });

        btnAnswerC.setBackground(new java.awt.Color(0, 51, 204));
        btnAnswerC.setForeground(new java.awt.Color(255, 255, 255));
        btnAnswerC.setText("C: AnswerC");
        btnAnswerC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick_C(evt);
            }
        });

        btnAnswerD.setBackground(new java.awt.Color(0, 51, 204));
        btnAnswerD.setForeground(new java.awt.Color(255, 255, 255));
        btnAnswerD.setText("D: AnswerD");
        btnAnswerD.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick_D(evt);
            }
        });

        btnWalkAway.setBackground(new java.awt.Color(0, 0, 153));
        btnWalkAway.setForeground(new java.awt.Color(204, 204, 255));
        btnWalkAway.setText("Walk Away");
        btnWalkAway.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClick_WalkAway(evt);
            }
        });

        pnlMoney.setBackground(new java.awt.Color(0, 0, 102));

        btn100.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn100.setForeground(new java.awt.Color(255, 204, 204));
        btn100.setText("$ 100");

        btn200.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn200.setForeground(new java.awt.Color(255, 204, 204));
        btn200.setText("$ 200");

        btn300.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn300.setForeground(new java.awt.Color(255, 204, 204));
        btn300.setText("$ 300");

        btn500.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn500.setForeground(new java.awt.Color(255, 204, 204));
        btn500.setText("$ 500");

        btn1000.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn1000.setForeground(new java.awt.Color(255, 204, 204));
        btn1000.setText("$ 1,000");

        btn2000.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn2000.setForeground(new java.awt.Color(255, 204, 204));
        btn2000.setText("$ 2,000");

        btn4000.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn4000.setForeground(new java.awt.Color(255, 204, 204));
        btn4000.setText("$ 4,000");

        btn8000.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn8000.setForeground(new java.awt.Color(255, 204, 204));
        btn8000.setText("$ 8,000");

        btn1600.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn1600.setForeground(new java.awt.Color(255, 204, 204));
        btn1600.setText("$ 16,000");

        btn32000.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn32000.setForeground(new java.awt.Color(255, 204, 204));
        btn32000.setText("$ 32,000");

        btn64000.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn64000.setForeground(new java.awt.Color(255, 204, 204));
        btn64000.setText("$ 64,000");

        btn125000.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn125000.setForeground(new java.awt.Color(255, 204, 204));
        btn125000.setText("$ 125,000");

        btn250000.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn250000.setForeground(new java.awt.Color(255, 204, 204));
        btn250000.setText("$ 250,000");

        btn500000.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn500000.setForeground(new java.awt.Color(255, 204, 204));
        btn500000.setText("$ 500,000");

        btn1000000.setFont(new java.awt.Font("Lucida Grande", 1, 13)); // NOI18N
        btn1000000.setForeground(new java.awt.Color(255, 204, 204));
        btn1000000.setText("$ 1,000,000");

        org.jdesktop.layout.GroupLayout pnlMoneyLayout = new org.jdesktop.layout.GroupLayout(pnlMoney);
        pnlMoney.setLayout(pnlMoneyLayout);
        pnlMoneyLayout.setHorizontalGroup(
            pnlMoneyLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(pnlMoneyLayout.createSequentialGroup()
                .addContainerGap()
                .add(pnlMoneyLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(btn100)
                    .add(btn200)
                    .add(btn300)
                    .add(btn500)
                    .add(btn1000)
                    .add(btn2000)
                    .add(btn4000)
                    .add(btn8000)
                    .add(btn1600)
                    .add(btn32000)
                    .add(btn64000)
                    .add(btn125000)
                    .add(btn250000)
                    .add(btn500000)
                    .add(btn1000000))
                .addContainerGap(94, Short.MAX_VALUE))
        );
        pnlMoneyLayout.setVerticalGroup(
            pnlMoneyLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, pnlMoneyLayout.createSequentialGroup()
                .addContainerGap()
                .add(btn1000000)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(btn500000)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btn250000)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btn125000)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btn64000)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btn32000)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btn1600)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btn8000)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btn4000)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btn2000)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btn1000)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btn500)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btn300)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btn200)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(btn100)
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(pnlQuestion, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, btnAnswerC, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, btnAnswerA, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(btnAnswerB, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(btnAnswerD, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)))
                    .add(layout.createSequentialGroup()
                        .add(pnlMoney, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                .add(btnWalkAway, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 121, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(9, 9, 9)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(17, 17, 17)
                        .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(btnWalkAway)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(pnlMoney, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(pnlQuestion, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnAnswerA)
                    .add(btnAnswerB))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnAnswerC)
                    .add(btnAnswerD))
                .add(7, 7, 7))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClick_A(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClick_A
        switch(selectedAnswer){
            case 'a':
                paintButton(btnAnswerA, ItemEvent.DESELECTED);
                selectedAnswer = 'n';
                break;
            case 'b':
                paintButton(btnAnswerB, ItemEvent.DESELECTED);
                paintButton(btnAnswerA, ItemEvent.SELECTED);
                selectedAnswer = 'a';
                break;
            case 'c':
                paintButton(btnAnswerC, ItemEvent.DESELECTED);
                paintButton(btnAnswerA, ItemEvent.SELECTED);
                selectedAnswer = 'a';
                break;
            case 'd':
                paintButton(btnAnswerD, ItemEvent.DESELECTED);
                paintButton(btnAnswerA, ItemEvent.SELECTED);
                selectedAnswer = 'a';
                break;
            default:
                paintButton(btnAnswerA, ItemEvent.SELECTED);
                selectedAnswer = 'a';
        }        
    }//GEN-LAST:event_btnClick_A

    private void btnClick_B(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClick_B
        switch(selectedAnswer){
            case 'a':
                paintButton(btnAnswerA, ItemEvent.DESELECTED);
                paintButton(btnAnswerB, ItemEvent.SELECTED);
                selectedAnswer = 'b';
                break;
            case 'b':
                paintButton(btnAnswerB, ItemEvent.DESELECTED);
                selectedAnswer = 'n';
                break;
            case 'c':
                paintButton(btnAnswerC, ItemEvent.DESELECTED);
                paintButton(btnAnswerB, ItemEvent.SELECTED);
                selectedAnswer = 'b';
                break;
            case 'd':
                paintButton(btnAnswerD, ItemEvent.DESELECTED);
                paintButton(btnAnswerB, ItemEvent.SELECTED);
                selectedAnswer = 'b';
                break;
            default:
                paintButton(btnAnswerB, ItemEvent.SELECTED);
                selectedAnswer = 'b';                
        }  
    }//GEN-LAST:event_btnClick_B

    private void btnClick_C(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClick_C
        switch(selectedAnswer){
            case 'a':
                paintButton(btnAnswerA, ItemEvent.DESELECTED);
                paintButton(btnAnswerC, ItemEvent.SELECTED);
                selectedAnswer = 'c';
                break;
            case 'b':
                paintButton(btnAnswerB, ItemEvent.DESELECTED);
                paintButton(btnAnswerC, ItemEvent.SELECTED);
                selectedAnswer = 'c';
                break;
            case 'c':
                paintButton(btnAnswerC, ItemEvent.DESELECTED);
                selectedAnswer = 'n';
                break;
            case 'd':
                paintButton(btnAnswerD, ItemEvent.DESELECTED);
                paintButton(btnAnswerC, ItemEvent.SELECTED);
                selectedAnswer = 'c';
                break;
            default:
                paintButton(btnAnswerC, ItemEvent.SELECTED);
                selectedAnswer = 'c';                
        }  
    }//GEN-LAST:event_btnClick_C

    private void btnClick_D(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClick_D
        switch(selectedAnswer){
            case 'a':
                paintButton(btnAnswerA, ItemEvent.DESELECTED);
                paintButton(btnAnswerD, ItemEvent.SELECTED);
                selectedAnswer = 'd';
                break;
            case 'b':
                paintButton(btnAnswerB, ItemEvent.DESELECTED);
                paintButton(btnAnswerD, ItemEvent.SELECTED);
                selectedAnswer = 'd';
                break;
            case 'c':
                paintButton(btnAnswerC, ItemEvent.DESELECTED);
                paintButton(btnAnswerD, ItemEvent.SELECTED);
                selectedAnswer = 'd';
                break;
            case 'd':
                paintButton(btnAnswerD, ItemEvent.DESELECTED);
                selectedAnswer = 'n';
                break;
            default:
                paintButton(btnAnswerD, ItemEvent.SELECTED);
                selectedAnswer = 'd';                
        } 
    }//GEN-LAST:event_btnClick_D

    private void btnClick_WalkAway(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClick_WalkAway
        gameReset();
        mainForm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnClick_WalkAway

    /** Paints the given Button based on the selection event. 
     * 
     * @param btn  The button of which state is changed
     * @param itmEvent  Shows whether the passed ToggleButton selected or deselected
     * 
     */
    private void paintButton(JButton btn, int itmEvent) {      
        if(itmEvent == ItemEvent.SELECTED){
            btn.setBackground(Color.yellow);
            btn.setForeground(Color.RED);
        }
        else{            
            float[] hsbcolor = Color.RGBtoHSB(0, 51, 204,null);
            btn.setBackground(Color.getHSBColor(hsbcolor[0], hsbcolor[1], hsbcolor[2]));
            btn.setForeground(Color.WHITE);
        }     
    }
    
    private void gameReset() {
        // Resets game variables
        // Should be changed
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn100;
    private javax.swing.JLabel btn1000;
    private javax.swing.JLabel btn1000000;
    private javax.swing.JLabel btn125000;
    private javax.swing.JLabel btn1600;
    private javax.swing.JLabel btn200;
    private javax.swing.JLabel btn2000;
    private javax.swing.JLabel btn250000;
    private javax.swing.JLabel btn300;
    private javax.swing.JLabel btn32000;
    private javax.swing.JLabel btn4000;
    private javax.swing.JLabel btn500;
    private javax.swing.JLabel btn500000;
    private javax.swing.JLabel btn64000;
    private javax.swing.JLabel btn8000;
    private javax.swing.JButton btnAnswerA;
    private javax.swing.JButton btnAnswerB;
    private javax.swing.JButton btnAnswerC;
    private javax.swing.JButton btnAnswerD;
    private javax.swing.JButton btnWalkAway;
    private javax.swing.JCheckBox chkAuditoryHelp;
    private javax.swing.JCheckBox chkCallFriend;
    private javax.swing.JCheckBox chkFiftyFifty;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblQuestion;
    private javax.swing.JPanel pnlMoney;
    private javax.swing.JPanel pnlQuestion;
    // End of variables declaration//GEN-END:variables
}
